# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zoorck's web
email: mserra95@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website designed to post some blog entries and also
  some code and personal discoveries.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zoorck.github.io" # the base hostname & protocol for your site
twitter_username: empty
github_username:  Zoorck

# Build settings
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown
